### PR TITLE
2015 08 study links

### PR DESCRIPTION
**Pull request by wibeasley**
@dani3876, here are some more changes, and many fixes related to the merge.  I hope I don't step on your toes again.

Also, I'm curious.  What do you use to edit the html?

### CODE REVIEW

**Comment by wibeasley** [comment]
@dani3876, ok, I'm done.  Pull (and upload to the webserver) if you're ok with the changes

**Comment by dani3876** [comment]
I've been using Notepad ++, but again, very novice at all of this and relying heavily on template so all fixes are appreciated!

**Comment by wibeasley** [comment]
I'm very glad to hear that.  While I was finishing, the sequence of commits, I started worrying that you were using some GUI editor that was doing that, and therefore likely to undue all my changes the next time any changes were made.

If you start doing a lot of webpage development, consider using NetBeans.  For what you want, I think you'd do fine with the ["HTML & PHP"](https://netbeans.org/downloads/) version.  It can check the correctness of your html code, and marks them with icons and squiggly line.  It has other nice features, such as auto-indent, which gets the nesting levels correct.  That was important when I tried to track down elements that were opened, but not closed.

However, it's likely some/most of those mistakes were introduced during the [bad/unnoticed merge](https://github.com/OuhscBbmc/BbmcResources/commit/0b02df8f3034f9ffff2b1b29a04c8b5c9084cfca#diff-d61fb6f43606c4e448ae7ea6dd22f072R314) last week, instead of during Notepad++ development.

**Comment by dani3876** [comment]
I will try NetBeans. Anything that can make the organization visible is extremely helpful to me.  

 And I didn't see that merge, or I may have messed it up when trying to manually incorporate the changes.   :)
Thanks again! I'm sure I'll be bugging you lots as we go.

**Pull request merged**
